title: PostgresCMS Blog
author: Alex
email: postgrescms@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Content management system that uses features of PostgreSQL databases.

# social links
github_username:  postgrescms

show_excerpts: true # set to false to remove excerpts on the homepage
